** Import the packages **


In [1]:
import numpy as np
import  pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**step-1 create a dataframe**
- we can create DF with list & dictionary

In [2]:
import pandas as pd
df1=pd.DataFrame()
type(df1)

pandas.core.frame.DataFrame

In [3]:
type(df1)

pandas.core.frame.DataFrame

In [4]:
name=['Aravind','Bhumika','Mayank']
pd.DataFrame(name)

0
0  Aravind
1  Bhumika
2   Mayank

In [5]:
name=['Aravind','Bhumika','Mayank']
df1=pd.DataFrame(name)
df1

0
0  Aravind
1  Bhumika
2   Mayank

**Step-3 Add columns**

In [6]:
df1=pd.DataFrame(name, columns=['Names'])
df1

Names
0  Aravind
1  Bhumika
2   Mayank

**Step 4: create dataframe usinng 2 lists**

In [7]:
name=['Aravind','Bhumika','Mayank']
age=[20,20,7]
df1=pd.DataFrame(zip(name,age), columns=['Name','Age'])
df1

Name  Age
0  Aravind   20
1  Bhumika   20
2   Mayank    7

**step 5: create a dataframe using three list**

In [8]:
name=['Aravind','Bhumika','Mayank']
age=[20,20,7]
city=['Hyd','Vadodara','USA']
cols=['Nmae','Age','City']
df1=pd.DataFrame(zip(name,age,city), columns=cols)
df1

Nmae  Age      City
0  Aravind   20       Hyd
1  Bhumika   20  Vadodara
2   Mayank    7       USA

In [9]:
name=['Aravind','Bhumika','Mayank']
age=[20,20,7]
city=['Hyd','Vadodara','USA']
cols=['Nmae','Age','City']
df1=pd.DataFrame(zip(name,age,city), columns=cols)
df1

Nmae  Age      City
0  Aravind   20       Hyd
1  Bhumika   20  Vadodara
2   Mayank    7       USA

**step-6 change the index**

In [10]:
- pd.dataframe takes 3 arguments, data, indes & columns

SyntaxError: invalid syntax (2441611488.py, line 1)

In [ ]:
name=['Aravind','Bhumika','Mayank']
age=[20,20,7]
city=['Hyd','Vadodara','USA']
cols=['Name','Age','City']
idx=['a','b','c']
df1=pd.DataFrame(zip(name,age,city), index=idx, columns=cols)
df1

In [ ]:
**step 7 : add new column on already existed dataframe**

- assume that dataframe already available and now need to addd new column

- new column values alsso in a form of list

- the length of the list equal to total number of rows

- df1[newcol]=list

In [ ]:
salary=['600','300','200']
df1['salaree']=salary
df1

In [ ]:
education=['lkg','ukg']
df1['edu']=education
df1

***ValueError: Length of values (2) does not match length of index (3)**

- length of index should match length of values

In [ ]:
**step 8: change the values of already existed column**

- if you want to add new column or if you want to modify the values of old column, the approach is same and syntax is same

- in both cases we need to make a list of values first & len of list should be equal to total number of rows

    - df['new column name'] = list

- to modify old columnn name

    -df['old column name'] = list

In [ ]:
**task**

- create 3 list 

- number list from 1to 10 ; square list 1 to 10; cube list from 1 to 10

- create dataframe

In [ ]:
numbers= [i for i in range(1,10)]
squre= [i*i for i in range (1,10)]
cube= [i*i*i for i in range(1,10)]
cols=['X','X^2','X^3']
df1=pd.DataFrame(zip(numbers,squre,cube), columns=cols)
df1


In [ ]:
import math
sqrroot=[ round(math.sqrt(i),2) for i in range(1,10)]  
df1['sqrroot']=sqrroot
df1

** creating empty DataFrame and adding colummns**


In [19]:
numbers= [i for i in range(1,10)]
squre= [i*i for i in range (1,10)]
cube= [i*i*i for i in range(1,10)]
cols=['X','X^2','X^3']
df3=pd.DataFrame()
df3['X^2']=squre
df3['x^3']=cube
#df3.drop('X',axis=1,inplace=True)
df3

X^2  x^3
0    1    1
1    4    8
2    9   27
3   16   64
4   25  125
5   36  216
6   49  343
7   64  512
8   81  729

In [ ]:
** step 9 : drop a column **

- drop is a method used to drop the columns & rows

- **axis** argument

    - axis=0 represents rows

    - axis=1 represents columns

- **inplace**

    - inplace=True

        - after dropping the rows or columns , the modified dataframe will be overwrite in the same name
    
    - inplace=False

        - Modified dataframe need to save in a new variable name

In [20]:
df3.drop('X',axis=1,inplace=True)
df3

KeyError: "['X'] not found in axis"

In [ ]:
**Step 10: rename the column**

- rename the column required a mapper function

- mapper is a dictionary

- old name will be act as key

- new name will be act as value

In [ ]:
df3
d={'X^2':'xSquare'}
df3.rename(columns=d)


**How to get all columns**

In [21]:
df3.columns

Index(['X^2', 'x^3'], dtype='object')

**renaming all column name**

In [22]:
df3.columns=['SQUARE','CUBE']
df3

SQUARE  CUBE
0       1     1
1       4     8
2       9    27
3      16    64
4      25   125
5      36   216
6      49   343
7      64   512
8      81   729

**step 12:How to select a column**

In [23]:
df3['SQUARE']

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
Name: SQUARE, dtype: int64

In [24]:
type(df3['SQUARE'])

pandas.core.series.Series

- Dataframe and series both look same

- Dataframe means a column name available

- Series means no column name

In [25]:
df3['SQUARE'].values

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int64)

- type: package

- list : basic python

- array: numpy

- Tensor: Tensorflow

In [14]:
# Covert list to array
import numpy as np
l=[1,2,3]
np.array(l)

array([1, 2, 3])

In [26]:
type(df3[['SQUARE']])

pandas.core.frame.DataFrame

In [27]:
df3[['SQUARE']].values

array([[ 1],
       [ 4],
       [ 9],
       [16],
       [25],
       [36],
       [49],
       [64],
       [81]], dtype=int64)

In [28]:
type(df3[['SQUARE']].values)

numpy.ndarray

In [29]:
arr1=df3['SQUARE'].values
arr2=df3[['SQUARE']].values
arr1.ndim,arr2.ndim

(1, 2)

- the more square brackets the dimention of the array increase

- []  single square is 1 dimension, [[]]  2 square brackets means 2 dimension and henceforth

**step 13: How to save the dataframe**

In [30]:
df3.to_csv('data1.xlsx')

In [32]:
type(df3.to_csv('ffvsf.csv'))

NoneType